os: linux
dist: bionic
language: node_js
node_js:
  - 12.16.1
cache: yarn
git:
  depth: false
branches:
  only:
    - develop
    - "/^epic\\/.*$/"
    - "/^release\\/.*$/"
    - "/^integration-libs\\/.*$/"
jobs:
  include:
    - script: "./ci-scripts/unit-tests-core-lib.sh"
      name: "Unit tests for core and storefrontlib"
    - script: "./ci-scripts/unit-tests.sh"
      name: "Unit tests for libs"
    - script: "./ci-scripts/validate-lint.sh"
      name: "Validation checks"
    - script: "export SPA_ENV='ci,b2b' && ./ci-scripts/e2e-cypress.sh -s b2b"
      name: "E2E tests for B2B, 1st job"
    - script: "export SPA_ENV='ci,b2b' && ./ci-scripts/e2e-cypress.sh -s b2b"
      name: "E2E tests for B2B, 2nd job"
    - script: "export SPA_ENV='ci,b2c' && ./ci-scripts/e2e-cypress.sh"
      name: "E2E tests for B2C, 1st job"
    - script: "export SPA_ENV='ci,b2c' && ./ci-scripts/e2e-cypress.sh"
      name: "E2E tests for B2C, 2nd job"
    - script: "export SPA_ENV='ci,b2c' && ./ci-scripts/e2e-cypress.sh"
      name: "E2E tests for B2C, 3rd job"
    - script: "export SPA_ENV='ci,b2c' && ./ci-scripts/e2e-cypress.sh"
      name: "E2E tests for B2C, 4th job"
    - script: "export SPA_ENV='ci,b2c' && ./ci-scripts/e2e-cypress.sh"
      name: "E2E tests for B2C, 5th job"
    - script: "./ci-scripts/e2e-cypress.sh --ssr"
      name: "E2E tests for SSR B2C"
    - script: "export SPA_ENV='cdc' && ./ci-scripts/e2e-cypress.sh -s cdc || exit 0"
      name: "E2E tests for CDC"
    - script: "./ci-scripts/lhci.sh"
      name: "Lighthouse score validation"
    - script: "export SPA_ENV='b2b,epd-visualization' && ./ci-scripts/e2e-cypress.sh -s epd-visualization || exit 0"
      name: "E2E tests for EPD Visualization"
      if: branch ~= /^.*epd-visualization.*$
addons:
  chrome: stable
  sonarcloud:
    organization: sap